Revert '[CI] Travis: removed all "++" in "clang++"' because clang will use C libraries and fail linking due to missing math libraries (undefined reference to fmod)
This reverts commit b2dbdd5f845bcb87fa92f04418b3e079c2c67036.